baseURL = "/"
languageCode = "en-us"
title = "Medicaid Gateway"
showToc = true
relativeURLs = true
disableKinds = ["taxonomy", "term"]

[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"

[markup]
  [markup.tableOfContents]
    ordered = false
