baseURL = "/"
languageCode = "en-us"
title = "Medicaid Gateway"
theme = "docsy"
showToc = true
relativeURLs = true
disableKinds = ["taxonomy", "term"]

[markup]
  [markup.tableOfContents]
    ordered = false
