---
registry:
  - namespace:
      - :mg_app
    features:
      - key: :state_abbreviation
        is_enabled: true
        item: "DC"
      - key: :transfer_to_enroll
        is_enabled: false
      - key: :transfer_service
        is_enabled: true
        item: "curam"
      - key: :mitc_determination
        is_enabled: true
      - key: :mec_check
        is_enabled: <%= ENV['MEC_CHECK_IS_ENABLED'] || false %>
      - key: :resubmit_to_enroll
        is_enabled: false
      - key: :bulk_transfer_to_enroll
        is_enabled: false
      - key: :fpl_overrides
        is_enabled: false
        item: [
                {
                  medicaid_year: 2021,
                  annual_poverty_guideline: BigDecimal(12_760.to_s),
                  annual_per_person_amount: BigDecimal(4_480.to_s)
                },
                {
                  medicaid_year: 2022,
                  annual_poverty_guideline: BigDecimal(12_880.to_s),
                  annual_per_person_amount: BigDecimal(4_540.to_s)
                }
              ]
      - key: :daily_determination_report
        is_enabled: true
      - key: :additional_ineligible_types
        is_enabled: true
      - key: :transfer_payload_type_atp
        is_enabled: <%= ENV["TRANSFER_PAYLOAD_TYPE_ATP"] || true %>
      - key: :transfer_payload_type_ios
        is_enabled: <%= ENV["TRANSFER_PAYLOAD_TYPE_IOS"] || false %>
      - key: :non_ssn_apply_reason
        is_enabled: <%= ENV["NO_SSN_APPLY_REASON_IS_ENABLED"] || false %>
      - key: :income_start_on
        is_enabled: <%= ENV["INCOME_START_ON_IS_ENABLED"] || false %>
      - key: :income_end_on
        is_enabled: <%= ENV["INCOME_END_ON_IS_ENABLED"] || false %>

