---
registry:
  - namespace:
    - :medicaid_gateway
    - :aces_integration
    features:
      - key: :aces_connection
        is_enabled: true
        settings:
          - key: :aces_atp_service_uri
            item: <%= ENV['ACES_ATP_SERVICE_URI'] %>
          - key: :aces_atp_service_username
            item: <%= ENV['ACES_ATP_SERVICE_USERNAME'] %>
          - key: :aces_atp_service_password
            item: <%= ENV['ACES_ATP_SERVICE_PASSWORD'] %>