development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: medicaid_gateway_development

test:
  adapter: async
  url: redis://localhost:6379/1
  channel_prefix: medicaid_gateway_test

production:
  adapter: redis
  url: redis://<%= ENV['REDIS_HOST_MEDICAID_GATEWAY'] %>:6379/1
  channel_prefix: medicaid_gateway_production
