---
registry:
  - namespace:
      - :mg_app
    features:
      - key: :state_abbreviation
        is_enabled: true
        item: "ME"
      - key: :transfer_to_enroll
        is_enabled: true
      - key: :transfer_service
        is_enabled: true
        item: "aces"
      - key: :mitc_determination
        is_enabled: true
      - key: :mec_check
        is_enabled: true
      - key: :resubmit_to_enroll
        is_enabled: false
      - key: :bulk_transfer_to_enroll
        is_enabled: true
      - key: :fpl_overrides
        is_enabled: false
      - key: :daily_determination_report
        is_enabled: false
      - key: :additional_ineligible_types
        is_enabled: false
      - key: :transfer_payload_type_atp
        is_enabled: <%= ENV["TRANSFER_PAYLOAD_TYPE_ATP"] || true %>
      - key: :transfer_payload_type_ios
        is_enabled: <%= ENV["TRANSFER_PAYLOAD_TYPE_IOS"] || false %>