---
registry:
  - namespace:
      - :mg_app
    features:
      - key: :state_abbreviation
        is_enabled: true
        item: "ME"
      - key: :transfer_to_enroll
        is_enabled: <%= ENV['TRANSFER_TO_ENROLL_IS_ENABLED'] || true %>
      - key: :transfer_service
        is_enabled: true
        item: "aces"
      - key: :mitc_determination
        is_enabled: true
      - key: :mec_check
        is_enabled: <%= ENV['MEC_CHECK_IS_ENABLED'] || true %>
      - key: :pdm_mec_check
        is_enabled: <%= ENV['PDM_MEC_CHECK_IS_ENABLED'] || true %>
      - key: :resubmit_to_enroll
        is_enabled: false
      - key: :bulk_transfer_to_enroll
        is_enabled: <%= ENV['BULK_TRANSFER_TO_ENROLL_IS_ENABLED'] || true %>
      - key: :fpl_overrides
        is_enabled: false
      - key: :daily_determination_report
        is_enabled: false
      - key: :additional_ineligible_types
        is_enabled: false
      - key: :transfer_payload_type_atp
        is_enabled: <%= ENV["TRANSFER_PAYLOAD_TYPE_ATP"] || true %>
      - key: :transfer_payload_type_ios
        is_enabled: <%= ENV["TRANSFER_PAYLOAD_TYPE_IOS"] || false %>
      - key: :drop_non_ssn_apply_reason
        is_enabled: <%= ENV["DROP_NON_SSN_APPLY_REASON_IS_ENABLED"] || false %>
      - key: :drop_income_start_on
        is_enabled: <%= ENV["DROP_INCOME_START_ON_IS_ENABLED"] || false %>
      - key: :drop_income_end_on
        is_enabled: <%= ENV["DROP_INCOME_END_ON_IS_ENABLED"] || false %>
      - key: :drop_vlp_document
        is_enabled: <%= ENV["DROP_VLP_DOCUMENT_IS_ENABLED"] || false %>
      - key: :drop_temp_out_of_state
        is_enabled: <%= ENV["DROP_TEMP_OUT_OF_STATE_IS_ENABLED"] || false %>
      - key: :invert_person_association
        is_enabled: <%= ENV["INVERT_PERSON_ASSOCIATION_IS_ENABLED"] || false %>
      - key: :block_atp_deductions
        is_enabled: <%= ENV["BLOCK_ATP_DEDUCTIONS_IS_ENABLED"] || false %>
      - key: :eligibility_override
        is_enabled: <%= ENV["ELIGIBILITY_OVERRIDE_IS_ENABLED"] || false %>
        settings:
          - key: :mitc_override_not_lawfully_present_pregnant
            item: <%= ENV["MITC_OVERRIDE_NOT_LAWFULLY_PRESENT_PREGNANT_IS_ENABLED"] || false %>
          - key: :mitc_override_not_lawfully_present_chip_eligible
            item: <%= ENV["MITC_OVERRIDE_NOT_LAWFULLY_PRESENT_CHIP_ELIGIBLE_IS_ENABLED"] || false %>
          - key: :mitc_override_not_lawfully_present_under_twenty_one
            item: <%= ENV["MITC_OVERRIDE_NOT_LAWFULLY_PRESENT_UNDER_TWENTY_ONE_IS_ENABLED"] || false %>
      - key: :medicaid_eligible_incarcerated
        is_enabled: <%= ENV["MEDICAID_ELIGIBLE_INCARCERATED_IS_ENABLED"] || false %>
      - key: :infer_post_partum_period
        is_enabled: <%= ENV["INFER_POST_PARTUM_PERIOD_IS_ENABLED"] || false %>
