source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in mitc_service.gemspec.
gemspec

# To use a debugger
# gem 'byebug', group: [:development, :test]

group :development, :test do
  gem "rspec-rails"
  gem "pry",        platform: :mri
  gem "pry-byebug", platform: :mri
  gem 'rubocop', '1.10.0'
  gem 'factory_bot_rails'
end
