################################################################
###                    Reports image                         ###
################################################################

ARG COMMIT_SHA
ARG CLIENT
ARG BRANCH=trunk

FROM public.ecr.aws/ideacrew/medicaid_gateway:${BRANCH}-${COMMIT_SHA}-${CLIENT}

USER root

RUN curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o "awscliv2.zip" && unzip awscliv2.zip && ./aws/install && rm awscliv2.zip 

USER $USERNAME
