---
registry:
  - namespace:
    - :medicaid_gateway
    features:
      - key: :to_ea
        is_enabled: false
      - key: :to_curam
        is_enabled: false
      - key: :to_aces
        is_enabled: false
