name: Docs and RSpec
on: push

jobs:
  mitc_service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wbari/start-mongoDB@v0.2
        with:
          mongoDBVersion: '4.2'
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
      - name: Cache Gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-medicaid_gateway-gems-mitc-service-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-medicaid_gateway-gems-mitc_service-${{ hashFiles('**/Gemfile.lock') }}
      - name: bundle install
        run: |
          bundle config path vendor/bundle
          bundle install
          cd components/mitc_service
          bundle config path ../../vendor/bundle
          bundle install
      - name: run tests
        run: |
          echo
          cd components/mitc_service
          bundle exec rspec
  rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Boot RabbitMQ
        run: |
          sudo apt-get update
          sudo apt-get install rabbitmq-server
          sudo rabbitmqctl add_vhost event_source
          sudo rabbitmqctl set_permissions -p event_source guest ".*" ".*" ".*"
      - uses: wbari/start-mongoDB@v0.2
        with:
          mongoDBVersion: '4.2'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
      - name: Cache Gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-medicaid_gateway-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-medicaid_gateway-gems-${{ hashFiles('**/Gemfile.lock') }}
      - name: bundle install
        run: |
          bundle config path vendor/bundle
          bundle install
      - name: run rubocop
        run: |
          bundle exec rubocop
      - name: run tests
        run: |
          sudo bash -c "echo '127.0.0.1 rabbitmq db' >> /etc/hosts"
          bundle exec rspec
  docs:
    needs:
      - mitc_service
      - rspec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: nelonoel/branch-name@v1.0.1
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: install hugo
        run: sudo snap install hugo --channel=extended
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: v2-${{ runner.os }}-gems-medicaid_gateway-${{ hashFiles('**/Gemfile.lock') }}-${{ hashFiles('**/Gemfile' ) }}
          restore-keys: |
            v2-${{ runner.os }}-gems-medicaid_gateway-${{ hashFiles('**/Gemfile.lock') }}-${{ hashFiles('**/Gemfile' ) }}
      - name: Install project gems
        run: |
          bundle config path vendor/bundle
          bundle install
      - name: Run yard
        run: bundle exec yard && cp -rf ./doc ./hugo/static/
      - run: cd hugo && npm install && hugo --minify
      - uses: nelonoel/branch-name@v1.0.1
      - uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: ${{ secrets.YARD_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.YARD_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.YARD_SECRET_ACCESS_KEY }}
          SOURCE_DIR: hugo/public
          DEST_DIR: ${{ env.BRANCH_NAME }}
