name: RSpec
on: push

jobs:
  rspec:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: wbari/start-mongoDB@v0.2
        with:
          mongoDBVersion: '4.2'
      - uses: mer-team/rabbitmq-mng-action@v1.2
        with:
          RABBITMQ_USER: 'guest'
          RABBITMQ_PASS: 'guest'
          RABBITMQ_PORT: 5672
          RABBITMQ_MNG_PORT: 15672
          RABBITMQ_TAG: '3-management-alpine'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Cache Gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-medicaid_gateway-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-medicaid_gateway-gems-${{ hashFiles('**/Gemfile.lock') }}
      - name: bundle install
        run: |
          bundle config path vendor/bundle
          bundle install
      - name: run rubocop
        run: |
          bundle exec rubocop
      - name: run tests
        run: |
          bundle exec rspec
        env:
          RABBITMQ_HOST: localhost
          RABBITMQ_VHOST: /
          RABBITMQ_PORT: 5672
          RABBITMQ_USERNAME: guest
          RABBITMQ_PASSWORD: guest
