---
registry:
  - namespace:
    - :curam_integration
    features:
      - key: :curam_connection
        is_enabled: true
        settings:
          - key: :curam_atp_service_uri
            item: <%= ENV['CURAM_ATP_SERVICE_URI'] %>
          - key: :curam_atp_service_username
            item: <%= ENV['CURAM_ATP_SERVICE_USERNAME'] %>
          - key: :curam_atp_service_password
            item: <%= ENV['CURAM_ATP_SERVICE_PASSWORD'] %>
          - key: :curam_check_service_uri
            item: <%= ENV['CURAM_ATP_CHECK_URI'] %>
          - key: :curam_mec_check_uri
            item: <%= ENV['CURAM_MEC_CHECK_URI'] %>
          - key: :curam_mec_check_username
            item: <%= ENV['CURAM_MEC_CHECK_USERNAME'] %>
          - key: :curam_mec_check_password
            item: <%= ENV['CURAM_MEC_CHECK_PASSWORD'] %>

